### ISSUE TITLE
Crash when initial profile creation is cancelled.

### ISSUE THREAD

**Issue by mkubecek** [LubosD/twinkle#22] opened 2015-07-18 09:27 UTC
Steps to reproduce:
1. Remove (or rename) ~/.twinkle so that it does not exist.
2. Start twinkle.
3. Confirm the information dialog.
4. Press "Profile editor".
5. Instead of entering a profile name, press "Cancel".

(Entering a profile name and pressing "Cancel" in the profile editor leads to the same result.)

The crash occurs in a separate thread but I have trouble finding where exactly as gdb cannot resolve the symbol. So far it seems that if `SelectProfileForm::execForm()` takes the "`return QDialog::Rejected`" path, some helper thread is left behind and crashes.

**Comment by LubosD** [comment] 2015-07-18 19:24
Interesting. Doesn't crash for me.

The only other existing threads seem to be owned by Qt itself. The first one is a QtScript thread, the other one is QXcbEventReader.

**Comment by aixtemaadmins** [comment] 2015-07-20 07:38
Doesn't crash for me either.
Cant reproduce it.

**Comment by fbriere** [comment] 2019-07-03 08:28
@mkubecek Would you have any objection to the closing of this issue?

I'm not really fond of dismissing valid bug reports without a proper resolution, but it seems rather unlikely we'll get one in this instance.  (Unless you can still reproduce this bug, of course.)

**Comment by olafdietsche** [comment] 2020-08-16 10:30
Doesn't crash here, exits with return code 1.
Ubuntu 20.04 (amd64), Twinkle 1:1.10.1+dfsg-4build2

**Comment by fbriere** [comment] 2022-02-19 02:46
Going ahead and closing.

**Closed by fbriere** 2022-02-19 02:46 UTC
Labels: bug, not reproducible
