### ISSUE TITLE
Unable to restore minimized main window

### ISSUE THREAD

**Issue by svergeylen** [LubosD/twinkle#121] opened 2018-05-17 12:14 UTC
In Ubuntu 18.04 LTS with Gnome 3, Twinkle correctly integrates in the top bar when clicking on the close icon, but there is no way to restore (reopen) that main window once closed. 

The menu seems not to contain a link to main window.
Clicking the Twinkle icon in the left menu trie to open a second instance of Twinkle, what fails.

The only workaround seems to kill twinkle and restart it (pretty bad).
Solution : add in the Twinkle menu an option to open main window

![twinkle](https://user-images.githubusercontent.com/2971168/40176718-a3b2940e-59dc-11e8-99db-1c845c9810e6.png)

**Comment by fbriere** [comment] 2018-08-14 02:07
A simple (left) click on the icon in the top bar should do the trick. :wink:  (If this does not work for you, please let us know, as this would indeed be a bug.)

That being said, it is true that most applications which embed themselves in the tray do provide a Show/Restore/Toggle menu entry, so I guess it would make sense for Twinkle to do the same.

**Comment by megagolgoth** [comment] 2019-01-06 21:07
I've got the exact same problem on Ubuntu with Mate desktop. When minimised on the dock, a clic (left or right) doesn't open the main window.
Apart this, Twinkle is the best SIP client I've got for now (and I tested a lot of clients).

**Comment by fbriere** [comment] 2019-07-03 06:43
@svergeylen I have just submitted a pull request that fixes the cause of this problem, namely that clicking on the system tray icon did not have any effect if "Hide in system tray when closing main window" was disabled.  However, your initial message states:

> Twinkle correctly integrates in the top bar when clicking on the close icon

which seems to imply that this option was actually enabled in your case.  Am I misreading you?

**Closed** 2020-02-23 08:45 UTC
Labels: GUI, bug, enhancement, info needed, pending

**Comment by stoyandimov** [comment] 2022-04-26 08:52
Here's a workaround if you are like me and haven't gotten this update via APT yet.
```
# opens the window without starting a new instance, if one is already running
twinkle --show
