### ISSUE TITLE
Does not properly support multiple WWW-Authenticate/Proxy-Authenticate headers

### ISSUE THREAD

**Issue by sherifshsffa91** [LubosD/twinkle#162] opened 2019-09-21 11:16 UTC
when i try to register my officesip account on twinkle for raspberry pi I get :

`registration failed: 401 Unauthorized`

while the log file shows the following :
```
`+++ 21-9-2019 13:14:33.958276 INFO SIP ::send_sip_tcp
Send to: tcp:192.168.1.2:5060
REGISTER sip:officesip.loc SIP/2.0
v: SIP/2.0/TCP 192.168.1.200;rport;branch=z9hG4bKosxcuqmr
Max-Forwards: 70
t: "sherif" <sip:444@officesip.loc>
f: "sherif" <sip:444@officesip.loc>;tag=vtmwi
i: zoctpocriuaofer@raspberrypi
CSeq: 760 REGISTER
m: <sip:444@192.168.1.200;transport=tcp>;expires=3600
Allow: INVITE,ACK,BYE,CANCEL,OPTIONS,PRACK,REFER,NOTIFY,SUBSCRIBE,INFO,MESSAGE
User-Agent: Twinkle/1.10.1
l: 0


---


+++ 21-9-2019 13:14:34.263919 INFO SIP ::process_sip_msg
Received from: tcp:192.168.1.2:5060
SIP/2.0 401 Unauthorized
v: SIP/2.0/TCP 192.168.1.200;rport;branch=z9hG4bKosxcuqmr
To:  "sherif" <sip:444@officesip.loc>;tag=1284b55e634b4d77a087a1ddf9002590
From:  "sherif" <sip:444@officesip.loc>;tag=vtmwi
Call-ID: zoctpocriuaofer@raspberrypi
CSeq: 760 REGISTER
x-Error-Details: No auth header
WWW-Authenticate: Digest realm="officesip.loc",nonce="1a4f79ac221f00c0074553415deb8b04",qop="auth",algorithm=MD5,stale=false,opaque="00000006"
WWW-Authenticate: NTLM targetname="officesip.loc",realm="OfficeSIP Server",version=3,opaque="4e074a7d"
x-Error-Details: No MS auth header
Date: Sat, 21 Sep 2019 11:14:31 GMT
WWW-Authenticate: Kerberos targetname="sip/officesip.loc",realm="OfficeSIP Server",version=3,opaque="4e074a7c"
x-Error-Details: No MS auth header
Date: Sat, 21 Sep 2019 11:14:31 GMT
Content-Length: 0


---


+++ 21-9-2019 13:14:34.264367 INFO NORMAL t_auth::authorize
Unsupported authentication scheme: Kerberos
---

`

```

while I am using officesip server with :
- domain name: officesip.loc
- user : 444
- password: 1234
- localhostIP: 192.168.1.2

and I tried testing the server from mobile app and it worked with no issue by the same user

**Comment by fbriere** [comment] 2019-09-21 15:41
I have just submitted #163 which should fix this issue.  Could you give it a try and confirm?  Thanks!

**Comment by sherifshsffa91** [comment] 2019-09-21 20:13
hello fbriere ,

I am using raspian os on raspberry pi so I am not able to find 

`src/parser/hdr_www_authenticate.cpp`
so can you help me find the way to get this file while 
I installed twinkle using : 

`sudo apt-get install twinkle `

**Comment by fbriere** [comment] 2019-09-22 00:51
@sherifshsffa91 This is not something you can fix in-place; you will have to cross-compile Twinkle from source (or most likely, find someone who can do it for you).  Unfortunately, I can't really help you with that; while I can easily provide `amd64` or `i386` packages, the Raspberry Pi uses a different architecture (`armel`, `armhf` or `arm64`, depending on the model).

In the meantime, you might want to check if you could possibly disable Kerberos and NT LAN Manager (NTLM) authentication support on your SIP server.  Basically, the issue is that when encountering such a reply:

```
WWW-Authenticate: Digest [...]
WWW-Authenticate: NTLM [...]
WWW-Authenticate: Kerberos [...]
```

Twinkle used to only remember the last method (Kerberos, which it does not support), forgetting that `Digest` (which is the only method it does support) had previously been offered.  If you could take away the other two choices, Twinkle would no longer be confused.

**Comment by sherifshsffa91** [comment] 2019-09-22 12:17
I were not able to reach this file 
 src/parser/hdr_www_authenticate.cpp~~~~ 

On Raspbian, to apply your fix. 

And when I tried to cross compile your source codes and found that this libraries you used is for not arm architecture. 
So i am going to change officeSIP server to any server else which works well with twinkle without the need of ntlm and kerberos support. 

So which server you recommend works well with twinkle

**Comment by fbriere** [comment] 2019-09-22 15:32
After reading a bit and playing around with cross-compiling, it doesn't look nearly as intimidating as I initially feared.  Might as well give it a try: could you tell me which release (see `/etc/os-release`) and architecture (`dpkg --print-architecture`) of Raspbian you are using?

**Comment by sherifshsffa91** [comment] 2019-09-22 15:40
hello fbriere ,

thanks for your help .

/etc/os-release 

`PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

`


dpkg --print-architecture 
`armhf`

**Comment by fbriere** [comment] 2019-09-22 17:11
I have uploaded Raspbian packages containing the fix for this issue at
https://github.com/fbriere/twinkle/tree/issue/162-multiple-auth-headers.raspbian-packages.  If I didn't screw up anything, they should do the trick.  (Knock on wood.)

**Closed** 2020-02-23 08:52 UTC
Labels: SIP, bug, pending
