### ISSUE TITLE
Crashing when opening with multiple profiles active

### ISSUE THREAD

**Issue by evandrocoan** [LubosD/twinkle#146] opened 2019-07-02 18:53 UTC
![image](https://user-images.githubusercontent.com/5332158/60538720-871e5f00-9ce1-11e9-8afe-069f39fb11fa.png)

It only works when I select just one profile.

**Comment by fbriere** [comment] 2019-07-02 19:47
I strongly suspect this is a duplicate of #88.  Could you try running Twinkle in a terminal and telling us what it prints out?

**Comment by evandrocoan** [comment] 2019-07-02 20:24
It printed this:
```
$ twinkle
qt5ct: using qt5ct plugin

(twinkle:26051): dbind-WARNING **: 17:23:54.941: Couldn't register with accessibility bus: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
Language name: "en"
qt5ct: D-Bus global menu: no
qt5ct: D-Bus system tray: no
inotify_add_watch("/home/evandro/.config/qt5ct") failed: "No space left on device"
terminate called after throwing an instance of 'std::logic_error'
  what():  Mutex lock failed
Aborted (core dumped)
```

**Comment by fbriere** [comment] 2019-07-02 22:21
Thanks.  Could you subscribe to #88?  I'll post a followup there and close this issue as a duplicate.

**Closed by fbriere** 2019-07-02 22:21 UTC
Labels: bug

**Comment by evandrocoan** [comment] 2019-07-02 22:22
Sure!
